services:
  domain:
    image: caddy:2.11.4
    container_name: domain
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ../..:/srv:ro
      - /var/www/github/jehpok.com/cloud/data:/nextcloud:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/www/github/jehpok.com/certs:/certs:ro

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - net

networks:
  net:
    external: true
