services:
  ai:
    build:
      context: ../../containers/ai
      dockerfile: Dockerfile

    container_name: ai
    restart: unless-stopped

    environment:
      MODEL_PATH: /models/qwen2.5-1.5b-instruct-q4_k_m.gguf

    volumes:
      - /var/www/llm:/models:ro

    expose:
      - "8000"

    networks:
      - web

networks:
  web:
    external: true
