import os
import re
import subprocess
import time
import signal
from pathlib import Path
from flask import Flask, request, redirect, render_template, Response

from mcrcon import MCRcon

SERVER_DIR = Path(os.environ.get("SERVER_DIR", "/server"))
SERVER_PROPERTIES = SERVER_DIR / "server.properties"
LOGS_DIR = SERVER_DIR / "logs"
LATEST_LOG = LOGS_DIR / "latest.log"

RCON_HOST = os.environ.get("RCON_HOST", "minecraft")
RCON_PORT = int(os.environ.get("RCON_PORT", "25575"))
RCON_PASSWORD = os.environ.get("RCON_PASSWORD", "change-me-via-dashboard")

CONTAINER = os.environ.get("MC_CONTAINER", "minecraft")

app = Flask(__name__)


# ── rcon helpers ──────────────────────────────────────────────────────────────

def rcon(cmd, timeout=3.0):
    """Run a single rcon command. Returns the response string or raises."""
    with MCRcon(RCON_HOST, RCON_PASSWORD, port=RCON_PORT, timeout=timeout) as r:
        return r.command(cmd)


def parse_tps(text):
    """Parse `debug` TPS section. Returns float tps (or None)."""
    # Example: " TPS from last 1m, 5m, 15m: 20.00, 19.98, 19.95"
    m = re.search(r"TPS from last 1m.*?:\s*([\d.]+)", text)
    return float(m.group(1)) if m else None


def stats():
    """Live stats from rcon."""
    out = {"online": None, "max": None, "tps": None, "uptime": None, "raw": ""}
    try:
        out["raw"] = rcon("list")
    except Exception as e:
        out["error"] = f"rcon: {e}"
        return out
    m = re.search(r"There are (\d+) of a max of (\d+) players online", out["raw"])
    if m:
        out["online"] = int(m.group(1))
        out["max"] = int(m.group(2))
    try:
        debug = rcon("debug")
        out["tps"] = parse_tps(debug)
    except Exception:
        pass
    # Container uptime via docker inspect (best-effort).
    try:
        s = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.StartedAt}}", CONTAINER],
            capture_output=True, text=True, timeout=2,
        )
        out["started_at"] = s.stdout.strip()
    except Exception:
        pass
    return out


# ── config (server.properties) ────────────────────────────────────────────────

# Fields exposed in the dashboard. Keep in sync with Paper's defaults.
EDITABLE_FIELDS = [
    "max-players", "gamemode", "difficulty", "hardcore", "pvp",
    "white-list", "view-distance", "simulation-distance",
    "motd", "spawn-protection", "level-seed", "level-type",
    "online-mode", "enable-command-block", "allow-flight",
    "server-port", "enable-rcon",
]


def read_properties():
    if not SERVER_PROPERTIES.exists():
        return {}
    out = {}
    for line in SERVER_PROPERTIES.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def write_properties(values):
    if not SERVER_PROPERTIES.exists():
        SERVER_PROPERTIES.write_text("# Generated by dashboard\n")
    text = SERVER_PROPERTIES.read_text()
    new_text_lines = []
    seen = set()
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            new_text_lines.append(line)
            continue
        k = stripped.split("=", 1)[0].strip()
        if k in values:
            new_text_lines.append(f"{k}={values[k]}")
            seen.add(k)
        else:
            new_text_lines.append(line)
    # Append any new fields.
    for k, v in values.items():
        if k not in seen:
            new_text_lines.append(f"{k}={v}")
    SERVER_PROPERTIES.write_text("\n".join(new_text_lines) + "\n")


# ── container control ─────────────────────────────────────────────────────────

def docker(action):
    """Start / stop / restart the game container. Stop+start to apply config."""
    if action not in ("start", "stop", "restart"):
        return False, "unknown action"
    if action == "restart":
        subprocess.run(["docker", "restart", CONTAINER], timeout=60)
        return True, "restarted"
    if action == "stop":
        subprocess.run(["docker", "stop", CONTAINER], timeout=60)
        return True, "stopped"
    subprocess.run(["docker", "start", CONTAINER], timeout=60)
    return True, f"{action}ed"


# ── routes ────────────────────────────────────────────────────────────────────

@app.errorhandler(404)
def not_found(e):
    return Response("not found", status=404, mimetype="text/plain")


@app.route("/healthz")
def healthz():
    return "ok", 200


@app.route("/", methods=["GET"])
def index():
    s = stats()
    props = read_properties()
    log_tail = ""
    if LATEST_LOG.exists():
        try:
            log_tail = "\n".join(LATEST_LOG.read_text(errors="ignore").splitlines()[-60:])
        except Exception:
            pass
    return render_template(
        "dashboard.html",
        stats=s,
        props=props,
        editable=EDITABLE_FIELDS,
        log_tail=log_tail,
        flash=request.args.get("flash"),
    )


@app.route("/control", methods=["POST"])
def control():
    action = (request.form.get("action") or "").strip()
    ok, msg = docker(action)
    return redirect(f"/?flash={msg}")


@app.route("/config", methods=["POST"])
def save_config():
    values = {}
    for k in EDITABLE_FIELDS:
        v = request.form.get(k)
        if v is not None and v != "":
            values[k] = v
    write_properties(values)
    # server.properties is hot-reloaded only for some keys. Restart to apply all.
    docker("restart")
    return redirect("/?flash=config+saved+and+server+restarted")


@app.route("/rcon", methods=["POST"])
def run_rcon():
    cmd = (request.form.get("cmd") or "").strip()
    if not cmd:
        return redirect("/?flash=empty+command")
    try:
        out = rcon(cmd)
    except Exception as e:
        return redirect(f"/?flash=rcon+error:+{e}")
    return redirect(f"/?flash={out[:200]}")


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
