#!/usr/bin/env bash
#
# scripts/nc-capture.sh — snapshot the LIVE Nextcloud user/group/quota state
# into config/nextcloud/{users,groups}.txt + default-quota. These are
# GENERATED recovery manifests: install.sh's nextcloud_setup recreates
# exactly what this captures on a fresh install — no hardcoded lists, so
# nothing drifts as users/groups change. Run `make nc-capture` on a healthy
# instance before wiping/migrating (and re-run it after any user change).
#
# Captures: every user (uid, quota, email, display name), every group with
# its members, and the files-app default quota for new users.
# Passwords are NOT captured (hashes are not portable) — the recovery
# generates new ones and prints them once.

set -uo pipefail

NC_CONTAINER="${NC_CONTAINER:-nextcloud}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_DIR/config/nextcloud"
OCC() { docker exec -u www-data "$NC_CONTAINER" php occ "$@"; }

docker ps --format '{{.Names}}' | grep -qx "$NC_CONTAINER" \
  || { echo "container $NC_CONTAINER not running"; exit 1; }

UIDS=$(OCC user:list 2>/dev/null | grep -oE '^  - [^:]+' | awk '{print $2}')
[ -n "$UIDS" ] || { echo "no users found"; exit 1; }

# ---------- users: uid|quota|email|displayname ----------
{
  echo "# GENERATED by make nc-capture ($(date -Is)) — do not edit; re-run to refresh."
  echo "# Format: uid|quota|email|displayname"
  for u in $UIDS; do
    info=$(OCC user:info "$u" 2>/dev/null)
    quota=$(echo "$info" | sed -n 's/^  - quota: //p')
    email=$(echo "$info" | sed -n 's/^  - email: //p')
    disp=$(echo "$info" | sed -n 's/^  - display_name: //p')
    echo "$u|${quota:-}|${email:-}|${disp:-}"
  done
} > "$OUT/users.txt"

# ---------- groups: group|member1,member2,... ----------
{
  echo "# GENERATED by make nc-capture ($(date -Is)) — do not edit; re-run to refresh."
  echo "# Format: group|member1,member2,..."
  for u in $UIDS; do
    # extract the groups section of user:info (between "groups:" and "quota:")
    info=$(OCC user:info "$u" 2>/dev/null)
    echo "$info" | awk '
      /^  - groups:/ { in_g=1; next }
      /^  - quota:/  { in_g=0 }
      in_g && /^    - / { sub(/^    - /, ""); print $0 " " "'"$u"'" }
    '
  done | sort -u | awk '{ g[$1] = g[$1] (g[$1] ? "," : "") $2 } END { for (k in g) print k "|" g[k] }' | sort
} > "$OUT/groups.txt"

# ---------- default quota for new users ----------
DQ=$(OCC config:app:get files default_quota 2>/dev/null | tail -1)
{
  echo "# GENERATED by make nc-capture ($(date -Is)) — do not edit; re-run to refresh."
  echo "# Default storage quota for NEW users (files app 'default_quota')."
  [ -n "$DQ" ] && echo "$DQ" || echo "#unset"
} > "$OUT/default-quota"

echo "captured $(echo "$UIDS" | wc -l) users -> $OUT/users.txt, $OUT/groups.txt, $OUT/default-quota"
