#!/usr/bin/env bash
# scripts/status.sh — the `make status` AIO dashboard.
#
# One aligned, colored, one-screen read of the live system: host perf
# (uptime, load, cpu, memory, swap, disk, top memory processes), the
# installed-module set, git, host units, failed units, docker containers,
# tmux, backups, mailboxes and the tailnet — one row per fact, no duplicate
# listings.
#
# Module-aware: reads $PROJECT_DIR/installed-modules.conf (GENERATED by
# scripts/install.sh — the same file `make smoke` reads). Rows for absent
# modules dim out instead of erroring; a missing conf = all assumed
# installed.
#
# No arguments. Colors auto-disable when stdout is not a tty or NO_COLOR is set.
set -uo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_DIR="$(dirname "$ROOT")"
CONF="$PROJECT_DIR/installed-modules.conf"
MODULES="cloud vault mail games monitor"
[ -f "$CONF" ] && MODULES="$(grep -vE '^[[:space:]]*(#|$)' "$CONF" | tr '\n' ' ')"
mod_in() { [[ " $MODULES " == *" $1 "* ]]; }

if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  B=$'\033[1m' D=$'\033[2m' R=$'\033[31m' G=$'\033[32m' Y=$'\033[33m' C=$'\033[36m' N=$'\033[0m'
else
  B='' D='' R='' G='' Y='' C='' N=''
fi

row()  { printf "  %s%-9s%s %s\n" "${C}${B}" "$1" "$N" "$2"; }
rule() { printf "  %s%s%s\n" "$D" "$(printf '%*s' 62 '' | tr ' ' '-')" "$N"; }

echo ""
printf "  %s%s%s — homelab status  %s· %s%s\n" "$B" "$(hostname)" "$N" "$D" "$(date '+%F %T %Z')" "$N"
rule

# host
up=$(cut -d. -f1 /proc/uptime)
up_d=$((up / 86400)); up_h=$(((up % 86400) / 3600))
. /etc/os-release 2>/dev/null || true
row host "${PRETTY_NAME:-Debian} · up ${up_d}d ${up_h}h"

# load + cpu
read -r l1 l5 l15 _ < /proc/loadavg
ncpu="$(nproc)"
lcol="$N"
awk -v v="$l15" -v n="$ncpu" 'BEGIN{exit !(v > n*2)}' && lcol="$R"
cpup=$(top -bn1 2>/dev/null | awk '/^%Cpu/{printf "%.0f", 100-$8; exit}')
row load "${lcol}${l1} ${l5} ${l15}${N} · cpu ${cpup:-?}% · ${ncpu} cores"

# memory + swap
m=$(free -b | awk '/^Mem:/{printf "%.1f/%.1f GiB", $3/1073741824, $2/1073741824}')
mp=$(free -b | awk '/^Mem:/{printf "%d", $3*100/$2}')
s=$(free -b | awk '/^Swap:/{if($2==0){print "none"; exit} printf "%.1f/%.1f GiB", $3/1073741824, $2/1073741824}')
mcol="$N"; [ "${mp:-0}" -ge 85 ] 2>/dev/null && mcol="$R"
row memory "${mcol}${m} (${mp:-?}%)${N} · swap ${s}"

# disk
dk=$(df -h / | awk 'NR==2{print $3"/"$2" ("$5")"}')
dp=$(df --output=pcent / 2>/dev/null | tail -1 | tr -dc '0-9')
dcol="$N"
[ "${dp:-0}" -ge 90 ] 2>/dev/null && dcol="$R"
[ "${dp:-0}" -ge 75 ] 2>/dev/null && dcol="$Y"
row "disk /" "${dcol}${dk}${N}"

# top memory processes
topmem=$(ps -eo comm,pmem --sort=-pmem --no-headers 2>/dev/null | head -3 \
  | awk '{printf "%s%s %.0f%%", (NR>1?" · ":""), $1, $2}')
row "top mem" "$topmem"

# installed modules (same conf `make smoke` reads)
mods=""
for m in cloud vault mail games monitor; do
  if mod_in "$m"; then mods+="${G}${m}${N}  "; else mods+="${D}${m}${N}  "; fi
done
if [ -f "$CONF" ]; then
  mods+="${D}(installed-modules.conf)${N}"
else
  mods+="${D}(conf missing — all assumed installed)${N}"
fi
row modules "$mods"

# git
if git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  gb=$(git -C "$ROOT" status -sb 2>/dev/null | head -1 | sed 's/^## //')
  gd=$(git -C "$ROOT" status --porcelain 2>/dev/null | wc -l)
  if [ "$gd" -gt 0 ]; then gs="${Y}${gd} uncommitted${N}"; else gs="${G}clean${N}"; fi
  row git "$gb · $gs"
fi

# host units
us=""
for u in ttyd dnsmasq goose; do
  if [ "$(systemctl is-active "$u" 2>/dev/null)" = active ]; then
    us+="${G}✓${N} $u  "
  else
    us+="${R}✗${N} $u  "
  fi
done
row units "$us"

# failed units
nf=$(systemctl --failed --no-legend 2>/dev/null | grep -c . || true)
if [ "${nf:-0}" = 0 ]; then
  row failed "${G}none${N}"
else
  fnames=$(systemctl --failed --no-legend 2>/dev/null | awk '{print $1}' | head -3 | tr '\n' ' ')
  row failed "${R}${nf} failed${N} ${D}${fnames}${N}"
fi

# docker
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  toks=()
  nunh=0
  while IFS=$'\t' read -r nm st; do
    [ -n "$nm" ] || continue
    case "$st" in
      *unhealthy*)  nunh=$((nunh+1)); toks+=("${R}${nm} ✗${N}");;
      *restarting*) nunh=$((nunh+1)); toks+=("${Y}${nm} ↻${N}");;
      *)            toks+=("${G}${nm}${N}");;
    esac
  done < <(docker ps --format '{{.Names}}\t{{.Status}}' 2>/dev/null)
  dhead="${#toks[@]} up"
  [ "$nunh" -gt 0 ] && dhead="${dhead} · ${R}${nunh} unhealthy${N}"
  row docker "$dhead"
  buf=""; i=0
  for t in "${toks[@]}"; do
    buf+="$t   "; i=$((i+1))
    if [ $((i % 5)) = 0 ]; then printf "            %s\n" "$buf"; buf=""; fi
  done
  [ -n "$buf" ] && printf "            %s\n" "$buf"
else
  row docker "${R}docker unavailable${N}"
fi

# tmux
if command -v tmux >/dev/null 2>&1; then
  tsess=$(tmux ls -F '#{session_name}' 2>/dev/null | tr '\n' ' ')
  if [ -n "$tsess" ]; then row tmux "$tsess"; else row tmux "${D}none${N}"; fi
fi

# backups
if [ -d "$PROJECT_DIR/backups" ]; then
  blist=$(ls -1t "$PROJECT_DIR/backups" 2>/dev/null)
  if [ -n "$blist" ]; then
    bn=$(echo "$blist" | wc -l)
    b3=$(echo "$blist" | head -3 | tr '\n' ' ')
    extra=""; [ "$bn" -gt 3 ] && extra=" ${D}(+$((bn-3)) older)${N}"
    row backups "$b3$extra"
  else
    row backups "${D}empty${N}"
  fi
else
  row backups "${D}none yet — make backup${N}"
fi

# mail (module-gated)
if mod_in mail; then
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx mailserver; then
    mb=$(docker exec mailserver setup email list 2>/dev/null | grep -c '@' || true)
    al=$(docker exec mailserver setup alias list 2>/dev/null | grep -c '@' || true)
    row mail "${mb:-0} mailboxes · ${al:-0} aliases"
  else
    row mail "${R}mailserver down${N}"
  fi
else
  row mail "${D}module not installed${N}"
fi

# tailnet
if command -v tailscale >/dev/null 2>&1 && ts_out=$(tailscale status 2>/dev/null); then
  tsip=$(echo "$ts_out" | head -1 | awk '{print $1}')
  peers=$(echo "$ts_out" | tail -n +2)
  non=$(echo "$peers" | grep -cw 'idle\|active' || true)
  noff=$(echo "$peers" | grep -cw 'offline' || true)
  pnames=$(echo "$peers" | awk '{print $2}' | head -4 | tr '\n' ' ')
  row tailnet "${tsip} · ${G}${non:-0} up${N} · ${D}${noff:-0} offline${N} · ${pnames}"
else
  row tailnet "${D}tailscale unavailable${N}"
fi

rule
echo ""