services:
  web:
    image: caddy:2
    container_name: web
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ../..:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/www/github/jehpok.com/certs:/certs:ro

    networks:
      - net

  tailscale:
    image: coredns/coredns:latest
    container_name: tailscale
    restart: unless-stopped

    ports:
      - "53:53/udp"
      - "53:53/tcp"

    volumes:
      - ./Corefile:/etc/coredns/Corefile:ro

    command: -conf /etc/coredns/Corefile

    networks:
      - net

networks:
  net:
    external: true